# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee1df310823da916a62fa18ff5e8ba3239608d4b0561a7c5138814247d6a7baa93ba7697fd3232c585ad9743d49de17477c942b299fdb0415a1d486133700fd9

test:
  secret_key_base: 705080c04e03cac096005763ddf1be5129a2d2ed997161d56b2e716b2c2984c02cb9e29581fe7a067e04ab7b39f7d7c905c675788efbba518a2ffe3eb7d8c977

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
